Update test.yml with flag infos and jacoco

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,14 +7,17 @@ on:
 jobs: 
   build:
     runs-on: ubuntu-latest
+
     strategy:
       matrix:
-        jvm_flag:
-          - "-Xmx512m"
-          - "-XX:+AlwaysPreTouch"
-          - "-XX:+UseG1GC"
-          - "-XX:+UseStringDeduplication"
-          - "-XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops"
+        jvm_flags: [
+          "-Xmx512m",
+          "-XX:+AlwaysPreTouch",
+          "-XX:+UseG1GC",
+          "-XX:+UseStringDeduplication",
+          "-XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops"
+        ]
+        common_jvm_flags_logs: [ "-XX:+UnlockDiagnosticVMOptions -Xlog:gc*:file=jvm.log:time,level,tags -XX:+PrintFlagsFinal" ]
 
     steps:
       # Checkout the repository
@@ -28,20 +31,48 @@ jobs:
           distribution: 'temurin'
           cache: maven
 
+      # Set environment variables for JVM flags and logs
+      - name: Set environment variables
+        run: |
+          echo "MAVEN_OPTS=${{ matrix.jvm_flags }} ${{ matrix.common_jvm_flags_logs }}" >> $GITHUB_ENV
+        shell: bash
+
       # Sanitize the JVM flag for artifact names
       - name: Sanitize JVM Flag
         id: sanitize
         run: |
-          sanitized_flag=$(echo "${{ matrix.jvm_flag }}" | sed 's/[:+]/_/g')
+          sanitized_flag=$(echo "${{ matrix.jvm_flags }}" | sed 's/[:+]/_/g')
           echo "sanitized_flag=$sanitized_flag" >> $GITHUB_ENV
 
       # Run Maven tests with different JVM flags and generate JaCoCo coverage report
       - name: Run Maven tests with JVM Flag and generate coverage report
-        run: |
-          echo "Running tests with JVM flag: ${{ matrix.jvm_flag }}"
-          mvn clean verify
+        timeout-minutes: 15
         env:
-          JVM_OPTS: ${{ matrix.jvm_flag }}
+          MAVEN_OPTS: "${{ matrix.jvm_flags }} ${{ matrix.common_jvm_flags_logs }}"
+        run: |
+          echo "Running tests with JVM flag: ${{ matrix.jvm_flags }}"
+          xvfb-run mvn clean verify jacoco:report -Pcoverage
+
+      # Process JaCoCo Coverage Report
+      - name: Get JaCoCo Coverage
+        id: coverage
+        run: |
+          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
+          echo "COVERAGE=$coverage" >> $GITHUB_ENV
+        shell: bash
+
+      # Fail if coverage has not improved
+      - name: Fail if coverage has not improved.
+        run: |
+          coverage=$COVERAGE
+          threshold=24.46
+          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then 
+            echo "Coverage is not improved."
+            exit 1
+          else
+            echo "New coverage: $coverage%. Coverage is improved!"
+          fi
+        shell: bash
 
       # Upload JaCoCo Coverage Report as an artifact with sanitized name
       - name: Upload JaCoCo Coverage Report
@@ -63,3 +94,9 @@ jobs:
         with:
           name: test-logs-${{ env.sanitized_flag }}
           path: logs/
+
+      # Display JVM Log
+      - name: Display JVM Log
+        if: always()
+        run: cat jvm.log
+        shell: bash
